# Example: Group - temp-team-a
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  annotations:
    github.com/project-slug: janus-idp-test/test-repo
spec:
  type: openapi
  lifecycle: production
  owner: team-test
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
